export const STATUS = {
    NONE: 'NONE',
    LOADING: 'LOADING',
    SUCCESS: 'SUCCESS',
    FAILURE: 'FAILURE',
}
//shippings
export const GET_SHIPPINGS_ATTEMPT = 'GET_SHIPPINGS_ATTEMPT';
export const GET_SHIPPINGS_SUCCEES = 'GET_SHIPPINGS_SUCCEES';
export const GET_SHIPPINGS_FAILURE = 'GET_SHIPPINGS_FAILURE';
//crear
export const CREATE_SHIPPING_ATTEMPT = 'CREATE_SHIPPING_ATTEMPT';
export const CREATE_SHIPPING_SUCCESS = 'CREATE_SHIPPING_SUCCESS';
export const CREATE_SHIPPING_FAILURE = 'CREATE_SHIPPING_FAILURE';
//actualizar
export const UPDATE_SHIPPING_ATTEMPT = 'UPDATE_SHIPPING_ATTEMPT';
export const UPDATE_SHIPPING_SUCCESS = 'UPDATE_SHIPPING_SUCCESS';
export const UPDATE_SHIPPING_FAILURE = 'UPDATE_SHIPPING_FAILURE';
//auth
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_FAILURE = 'AUTH_REGISTER_FAILURE';
